server:
  port: 16004
  contextPath: /console
spring:
  application:
    name: paymentApi # lower case fo application name
  mustache:
    check-template-location: false

logging:
  path: ./logs
  file: ./logs/console.log