//package com.hyj.application;
//
//
//import org.springframework.beans.factory.annotation.Value;
//import org.springframework.context.annotation.Bean;
//import org.springframework.context.annotation.Configuration;
//
//import springfox.documentation.builders.ApiInfoBuilder;
//import springfox.documentation.builders.RequestHandlerSelectors;
//import springfox.documentation.service.ApiInfo;
//import springfox.documentation.service.Contact;
//import springfox.documentation.spi.DocumentationType;
//import springfox.documentation.spring.web.plugins.Docket;
//
//@javax.annotation.Generated(value = "class io.swagger.codegen.languages.SpringCodegen", date = "2016-12-14T10:43:41.109+08:00")
//
//@Configuration
//public class SwaggerDocumentationConfig {
//
//	@Value("${swagger.enable}")
//	private Boolean swaggerEnable;
//	
//    ApiInfo apiInfo() {
//        return new ApiInfoBuilder()
//            .title("全宇宙最流弊支付平台系统之API接口")
//            .description("No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)")
//            .license("")
//            .licenseUrl("")
//            .termsOfServiceUrl("")
//            .version("")
//            .contact(new Contact("","", ""))
//            .build();
//    }
//
//    @Bean
//    public Docket customImplementation(){
//        return new Docket(DocumentationType.SWAGGER_2)
//        		.enable(swaggerEnable)
//                .select()
//				.apis(RequestHandlerSelectors.basePackage("com.yck.payment.controller"))
//				.build()
//                .directModelSubstitute(org.joda.time.LocalDate.class, java.sql.Date.class)
//                .directModelSubstitute(org.joda.time.DateTime.class, java.util.Date.class)
//                .apiInfo(apiInfo());
//    }
//
//}
